openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Simple contact application, that will help you to keep all our important connections in one place
tags:
  - name: Contacts
    description: Operations with Contacts
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-gufi.onrender.com
paths:
  /contacts:
    get:
      $ref: "../swagger/paths/contacts/get.yaml"
    post:
      $ref: "../swagger/paths/contacts/post.yaml"
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: "../swagger/paths/contacts/{id}/patch.yaml"
    delete:
      $ref: "../swagger/paths/contacts/{id}/delete.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
